### ISSUE TITLE
read_rpt() not capable of reading rpt file when exponents are included (i.e. when storage units are included in model)

### ISSUE THREAD

**Issue by schuetzpaul** [dleutnant/swmmr#112]
swmmr::read_rpt() is not capable of reading/loading the rpt.file when an exponent is included.
In my example this is the case when a storage unit is included in the model:

`rpt_file <- swmmr::read_rpt("/00_template.rpt")`

![grafik](https://user-images.githubusercontent.com/132555375/236453541-4bffd964-a219-43f2-a712-d0696b108301.png)

In R, the following Error appears:

`Error in sub(re, "", x, perl = TRUE) : input string 212 is invalid UTF-8`

**Comment by hsonne** [comment]
If you are on Windows, please try the following workaround. It tells the `read_rpt()` function how characters are encoded in the file: 
```
rpt_file <- swmmr::read_rpt("/00_template.rpt", locale = readr::locale(encoding = "WINDOWS-1252"))
```
Does that work for you?

**Comment by schuetzpaul** [comment]
Yes, works perfectly, thanks!
