### ISSUE TITLE
.out file is not working in linux operating syatem

### ISSUE THREAD

**Issue by ved-ux** [dleutnant/swmmr#117]
Hi @dleutnant,

I hope you're doing well. I wanted to express my appreciation for the development of swmmr; it's truly commendable to see efforts aimed at enhancing the accessibility and usability of crucial environmental modeling software like SWMM. The seamless integration with R and the provision of fast access to simulation results are invaluable features that can greatly benefit researchers, engineers, and policymakers involved in water management and environmental protection.

On a different note, I've been encountering difficulties while trying to open the output file using RStudio on Ubuntu 22.04. Whenever I execute the line of code 

"out_object <- read_out(swmm_files$out)", 

RStudio crashes consistently. I've been troubleshooting this issue for about a week now, but unfortunately, I haven't been able to find a solution. I would greatly appreciate any suggestions or guidance you might have on resolving this issue. I will be happy to share any further details that might be helpful in diagnosing the problem. 

Thank you so much for your time and assistance.

**Comment by hsonne** [comment]
Hi @ved-ux,

did you try to install the development version of swmmr? See here: https://github.com/dleutnant/swmmr/issues/52#issuecomment-1397724098

**Comment by ved-ux** [comment]
Hi @dleutnant  , thank you. Now it is working.
