### ISSUE TITLE
Incomplete parsing of LID performance results in rpt file

### ISSUE THREAD

**Issue by yudb** [dleutnant/swmmr#14]
[1yr-1hr-min.zip](https://github.com/dleutnant/swmmr/files/2123172/1yr-1hr-min.zip)
please help me,thank you~

**Comment by yudb** [comment]
![image](https://user-images.githubusercontent.com/3918816/41713916-36be0bba-7581-11e8-91ce-615bc3020a17.png)
report$subcatchment_runoff_summary
i can't find  LID performance results

**Comment by dleutnant** [comment]
oh, looks like there is a parsing error. Any ideas, @maltehenrichs?

**Comment by dleutnant** [comment]
We fixed this issue in a0e0cbadc1496ca575500db0f01ffa81b50f2a8e. Could you please confirm?

**Comment by dleutnant** [comment]
I am closing this issue for now as communication did not continue.
