### ISSUE TITLE
shp_to_inp coordinates for outfall are missing

### ISSUE THREAD

**Issue by fcfunke** [dleutnant/swmmr#15]
I'm using shp_to_inp to create an input file out of my shapefiles (subcatchments, conduits, junctions, outfall). 
It is working for all except the outfall where coordinates in swmm are missing. 

My impression: Coordinates for junctions are saved but the outfall is not.
list_of_sections[["coordinates"]] <- junction
(Zeile 226 in https://github.com/dleutnant/swmmr/blob/master/R/shp_to_inp.R) 

thank you for help

**Comment by dleutnant** [comment]
@DoeringA Any idea?

**Comment by fcfunke** [comment]
It works if I include the outfall (Out1) in both path_point and path_outfall and remove it from $junction afterwards.  
example1<-shp_to_inp(
  path_polygon = file.path(directory,outsub),
  path_point = file.path(directory,outnod),
  path_outfall = file.path(directory,outout),
  path_line = file.path(directory,outcon),
  subcatchment_typologies = subcatchment_typologies,
  infiltration = infiltration)

example1$junction <- example1$junction[example1$junction$Name != "Out1", ]
write_inp(example1,input)

**Comment by dleutnant** [comment]
Is this issue still unsolved? Otherwise please consider to close and comment. Thanks!

**Comment by DoeringA** [comment]
In the current version the coordinate section is only made for junction nodes. As dickinsonre commented, looping over the whole range of nodes still needs to be implemented. Currently, coordinates for other than junction nodes, must be added to the inp object manually (inp$coordinates).

**Comment by dleutnant** [comment]
#39
