### ISSUE TITLE
run_swmm unable to run ... cannot find .rpt and .out

### ISSUE THREAD

**Issue by ngg-osu** [dleutnant/swmmr#17]
Hi,

I'm trying to run a saved inp file in a new directory, but for some reasons, it couldn't run as it can't find  .rpt and .out file ( which shouldn' t be there in the first place, since it is run for the first time).

Any advice? Thanks!

> results <- run_swmm("test-swmmr.inp", exec="E:/EPA-SWMM-5.1.013")
Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="./test-swmmr.rpt": The system cannot find the file specified
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="./test-swmmr.out": The system cannot find the file specified

**Comment by maltehenrichs** [comment]
Did you check if the "exec" file exists? Normally it should be: "C:\Program Files (x86)\EPA SWMM 5.1.013\swmm5.exe"
Perhaps in your case "E:/EPA-SWMM-5.1.013/swmm5.exe"

**Comment by dleutnant** [comment]
@ngg-osu Any news? Issue still unsolved? Otherwise please consider to close and comment. Thanks!

**Comment by dleutnant** [comment]
#2

**Comment by ngg-osu** [comment]
thanks @dleutnant , i tried to open, run and close inp file in SWMM, then somehow it worked. Not sure what exactly happened. But thanks for the attention!
