### ISSUE TITLE
Simulation Time calibration

### ISSUE THREAD

**Issue by knraj** [dleutnant/swmmr#20]
Currently simulation results are calculated for 24 hrs. How to dynamically adjust the simulation time so that the simulation run can be adjusted accordingly?

**Comment by dleutnant** [comment]
I'm not quite sure what you mean. If you need to programmatically modify the simulation duration, I'd read the .inp file, edit the corresponding entries of section `options` (START_DATE, START_TIME, REPORT_START_DATE, REPORT_START_TIME),  write the modified .inp file to disk and init the simulation run. Does this help you?

**Comment by dleutnant** [comment]
I'm closing this issue as the communication did not continue.
