### ISSUE TITLE
read_rpt does not account for all report sections

### ISSUE THREAD

**Issue by HamedGhodsi90** [dleutnant/swmmr#21]
Hi Dominik,

I have used your package. It is great But it has some problems. For example in the read_rpt section, for using a report file which has more sections, your package cannot recognize them.  I have prepared a complete list which I suggest you replace them.

report_sections <- c("Element Count",
                     "Pollutant Summary",
                     "Landuse Summary",
                     "Raingage Summary",
                     "Subcatchment Summary",
                     "LID Control Summary",
                     "Node Summary",
                     "Link Summary",
                     "Cross Section Summary",
                     "Analysis Options",
                     #"Rainfall File Summary",
                     #"Rainfall Dependent I/I",
                     #"Control Actions Taken",
                     "Runoff Quantity Continuity", 
                     "Runoff Quality Continuity",
                     #"roundwater Continuity",
                     "Flow Routing Continuity",
                     "Quality Routing Continuity",
                     #"Highest Continuity Errors",
                     #"Time-Step Critical Elements",
                     "Highest Flow Instability Indexes", 
                     "Routing Time Step Summary", 
                     #"Subcatchment Results",
                     "Subcatchment Runoff Summary",
                     "Subcatchment Washoff Summary",
                     "LID Performance Summary",
                     "Groundwater Summary",
                     #"Node Results",
                     "Node Depth Summary", 
                     "Node Inflow Summary", 
                     "Node Surcharge Summary",
                     "Node Flooding Summary", 
                     "Storage Volume Summary",
                     "Outfall Loading Summary", 
                     #"Link Results",
                     "Link Flow Summary", 
                     "Flow Classification Summary",
                     "Conduit Surcharge Summary",
                     "Pumping Summary",
                     "Link Pollutant Load Summary")

**Comment by dleutnant** [comment]
Thank you @HamedGhodsi90. I am quite busy with other projects at the moment, so integrating your suggestion may take a while. However, If you would like to prepare a pull request I would be happy to review your code changes. What do you think?

**Comment by dleutnant** [comment]
to solve this issue, the following has to be done:

- [ ] extend vector with all possible report sections
- [ ] add a new function `parse_section.SECTION_NAME` for each added section

**Comment by dleutnant** [comment]
All sections are now integrated. See cca4c90fca30576597b1cd1ab207703710f795fb. One Issue #26 about rpt parsing remains.

**Comment by HamedGhodsi90** [comment]
Hi,
I hope all is well with you.

A new problem is detected when I am using the read_inp() function. The
error is:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
namespace ‘vctrs’ 0.1.0 is being loaded, but >= 0.2.0 is required

It was right until the last week. This error is something new, I am
wondering if you could try this function and see if the same error would be
appeared or not. If yes, it would be great if you could modify it and
release a new version of that.

Thanks.

**Comment by HamedGhodsi90** [comment]
The problem is solved.
Thanks in advance.
Sorry for the inconvenience.

Best wishes,
Hamed
