### ISSUE TITLE
Zenodo DOI

### ISSUE THREAD

**Issue by mrustl** [dleutnant/swmmr#29]
@dleutnant would be cool if you get a Zenodo DOI for citing your R package:
https://guides.github.com/activities/citable-code/

**Comment by dleutnant** [comment]
Hopefully this will soon no longer be necessary ;)

**Comment by mrustl** [comment]
Sorry I didn`t get that. Does CRAN plan to assign a DOI for all R packages?

**Comment by dleutnant** [comment]
For the record there is now an open access paper about the package available: https://doi.org/10.1080/1573062X.2019.1611889
