### ISSUE TITLE
Green-Ampt parameters

### ISSUE THREAD

**Issue by maxbekas** [dleutnant/swmmr#32]
Could you share the example of supplementary R objects for Infiltrarion for Green-ampt method? All the examples include only Horton's parameters
Thanks!

**Comment by maxbekas** [comment]
Or maybe the right name for columns in .shp files for Green-Ampt.

**Comment by dleutnant** [comment]
Well, I'm about to go on vacation. So things may take a while.

**Comment by maxbekas** [comment]
Have a nice rest!

**Comment by jjsoper** [comment]
Are there any updates on this? I just found that read_inp doesn't seem to support the Modified Green-Ampt equations. Works fine when I switch over to Horton.

Thanks

**Comment by dickinsonre** [comment]
The Modified GA was added in 2015 and in some respects is the best infiltration option

Build 5.1.010 (08/05/15)
Engine Updates:
1.	A modified version of Green-Ampt infiltration (MODIFIED GREEN AMPT) was added that no longer redistributes upper zone moisture deficit during low rainfall events. The original authors of SWMM's Green-Ampt model have endorsed this modified version. It will produce more infiltration for storm events that begin with low rainfall intensities, such as the SCS design storm distributions.

**Comment by jjsoper** [comment]
This looks to be a simple fix in the code. The modified Green-Ampt column headers are the same as Green-Ampt (see [SWMM user manual](https://www.epa.gov/sites/default/files/2019-02/documents/epaswmm5_1_manual_master_8-2-15.pdf) page 290). Simply duplicating the headers in the parse_section.infiltration options and renaming to modified_green_ampt does the trick.

https://github.com/jjsoper/swmmr/blob/21b91d978ae9a03ebedd1e37a9984ad5e154a01a/R/parse_section.R#L177-L196

@hsonne I think your latest mydev branch is the most up to date (handles large .out files and seems to support R 4.02) and is what I have been using.
https://github.com/dleutnant/swmmr/issues/48#issue-653099692

**Comment by hsonne** [comment]
@jjsoper I changed `parse_section.infiltration()` according to your suggestion and did some cleaning (see https://github.com/hsonne/swmmr/pull/5/files). Would you like to test this by installing swmmr from my "support-modified-green-ampt" branch?
```
remotes::install_github("hsonne/swmmr@support-modified-green-ampt")
```

**Comment by jjsoper** [comment]
@hsonne yes will do. Heading out for vacation but will test when I get back (2/14). Thanks!

**Comment by jjsoper** [comment]
@hsonne can confirm that this works on my computer. Thanks!

**Comment by hsonne** [comment]
The corresponding changes are now available on the `dev` branch of this repository. 
You can install the package from there with `remotes::install_github("dleutnant/swmmr@dev")`.
