### ISSUE TITLE
swmm plugin

### ISSUE THREAD

**Issue by trasto21** [dleutnant/swmmr#42]
i'm trying to use your plugin with qgis 3.12.2 but there are any missing content in the downloaded file. i need a procedure to import in swmm 5.1 from a qgis' shape file. i hope you can send me a solution.
thanks

Valerio

**Comment by dleutnant** [comment]
Are you using `{swmmr}` with the data exported by QGEP (https://github.com/QGEP/QGEP/issues/571)? I haven’t used the data structure from QGEP and can’t say what it contains and how it exports data. 

`{swmmr}`, however is able to import ESRI’s old fashioned .shp files but still needs some additional information (e.g. curves, time series data, etc.). Please make sure to check the vignette from @DoeringA  (https://cran.r-project.org/web/packages/swmmr/vignettes/How_to_convert_between_GIS_data_and_SWMM_with_swmmr.html).

**Comment by trasto21** [comment]
thanks for the answer, but i should do the opposite process, that is import from a shape file into a swmm inp file. please let me know if it's able with your plugin.
thanks

**Comment by dleutnant** [comment]
Please make sure to check the vignette from @DoeringA (https://cran.r-project.org/web/packages/swmmr/vignettes/How_to_convert_between_GIS_data_and_SWMM_with_swmmr.html).

**Comment by trasto21** [comment]
sorry but i can't find the plugin swmmr for qgis 3.12, which is the qgis version i can use to find it?

**Comment by dleutnant** [comment]
`{swmmr}` is an R package. You could install [R](https://www.r-project.org/), execute `install.packages("swmmr") ` and follow the instructions given in the vignette.

**Comment by dleutnant** [comment]
I am closing this issue, as I think your question is answered. Please reopen if you need further support.
