### ISSUE TITLE
Write_inp function prints node coordinates in [JUNCTIONS] section

### ISSUE THREAD

**Issue by Enrilok** [dleutnant/swmmr#44]
Hello, I have a problem related to the ```write_inp``` function as this prints the coordinates of the nodes in the [JUNCTIONS] section next to the "Aponded" item as shown in the following image:
![1](https://user-images.githubusercontent.com/60235002/82191944-8db2c680-98f3-11ea-94d5-bc8e7a971062.PNG)

Unfortunately, this is not expected from the formatting of the SWMM .inp file and creates the error "List index out of bounds (0)" when trying to open the .inp file created by the SWMM DOWN interface. Can you help me to prevent the ```write_inp``` function from printing this column? I report the created .inp file that contains the coordinates that create the error. Thank you very much for helping,
Enrico
[PAULLO_JUNCTIONS.ERROR.txt](https://github.com/dleutnant/swmmr/files/4643020/PAULLO_JUNCTIONS.ERROR.txt)

**Comment by dleutnant** [comment]
You have two options: 1) tidy the column of the  junctions data.frame or 2) make sure that the data.frame "junctions" contains only valid data at first place (i.e. before you write the .inp).

@Enrilok Please remember, the chances of getting support increase when you supply a fully reproducible example. Also, as we are on GITHUB, please feel free to look at the code basis to see where the potential issue may originate from.

**Comment by Enrilok** [comment]
Thanks for the reply, I am in fact checking the script of the ```shp_to_inp``` function as it generates a "geometry" column containing the coordinates of the nodes in the [JUNCTIONS] section (which was not entered by me in the shapefile), but I cannot find the error. In any case I solved it by removing this column from the struct as the coordinates of the nodes are correctly entered in the [COORDINATES] section. 
Specifically, I simply added the following line at the end of building the struct (PAULLO in my case)
```
PAULLO$junctions$geometry <- NULL
```
I'm sorry to disturb, but I prefer to report the problems I encounter in case they may be useful, thanks in any case for your help!
Enrico

**Comment by dleutnant** [comment]
> I'm sorry to disturb, but I prefer to report the problems I encounter in case they may be useful, thanks in any case for your help!

Your feedback is very much appreciated!

**Comment by dleutnant** [comment]
> ...  but I cannot find the error."

Could you please elaborate on this? Which steps did you do? How does your original .inp file look like?

**Comment by Enrilok** [comment]
I make an introduction: I started from the shapefiles of my sewer network, created in accordance with the manual of the swmmr package, then using the ```shp_to_inp``` function and the ```write_inp``` function I created the .inp file for modeling in SWMM, then adding some sections from external excel files. The .inp file is created correctly (the .inp file is PAULLO_CORRECT which I inserted below) but when I open it  with SWMM (last release 5.1.014) I receive the error "List index out of bounds (0)"
![2](https://user-images.githubusercontent.com/60235002/82208647-31a86c00-990c-11ea-81a0-48b41e3cb973.PNG)
and I noticed that this error occurs the moment I insert it the two sections [BUILDUP] and [WASHOFF] although these are created in accordance with the SWMM manual. If in fact I do not enter these two sections, the error does not appear and the .inp file is read perfectly by SWMM.

 I was at this point checking the structure of the .inp file created and I realized that in the [JUNCTIONS] section next to the "Aponded" item also the coordinates of the nodes appeared and since this is incorrect according to the SWMM manual I tried to understand if that was the problem. Unfortunately this is not the case and even removing this column of coordinates I keep getting the same error. I report the .inp file created initially containing these coordinates in the [JUNCTIONS] section, the correct one by removing this column and my code. If you need it, I also attach the shapefiles and the added sections from which I started (contained in Paullo.zip). Can you open my .inp (PAULLO_CORRECT) file without the "List index out of bounds" error? do you have any suggestions that i can apply?
Thanks a lot for your help!

[PAULLO_JUNCTIONS.ERROR.txt](https://github.com/dleutnant/swmmr/files/4643866/PAULLO_JUNCTIONS.ERROR.txt)
[PAULLO_CORRECT.txt](https://github.com/dleutnant/swmmr/files/4643884/PAULLO_CORRECT.txt)
[Paullo.zip](https://github.com/dleutnant/swmmr/files/4643939/Paullo.zip)

```
out_dir <- "C:/Users/Enrico/Tesi/Paullo"

PAULLO <- shp_to_inp(
  path_options = file.path(out_dir,"SECTIONS/SWOPTIONS.txt"),
  path_polygon = file.path(out_dir,"SWMM/Paullo_polygon.shp"),
  path_line = file.path(out_dir,"SWMM/Paullo_link.shp"),
  path_point = file.path(out_dir,"SWMM/Paullo_point.shp"),
  path_outfall = file.path(out_dir,"SWMM/Paullo_outfall.shp"),
  path_pumps = file.path(out_dir,"SWMM/Paullo_pumps.shp"),
  path_storage = file.path(out_dir,"SWMM/Paullo_storages.shp"),
  path_weirs = file.path(out_dir,"SWMM/Paullo_weirs.shp"),
)

#JUNCTIONS COORDINATES CORRECTION
PAULLO$junctions$geometry <- NULL

INFILTRATION <- read_excel("SECTIONS/INFILTRATION.xlsx")
  PAULLO$infiltration <- (INFILTRATION)
XSECTIONS <- read_excel("SECTIONS/XSECTIONS.xlsx")
  PAULLO$xsections <- dplyr::bind_rows(PAULLO$xsections, XSECTIONS)
CONTROLS <- read_csv("SECTIONS/CONTROLS.txt", col_names = FALSE, col_types = cols())
  PAULLO$controls <- (CONTROLS)
CURVES <- read_excel("SECTIONS/CURVES.xlsx")
  PAULLO$curves <- (CURVES)
REPORT <- read_excel("SECTIONS/REPORT.xlsx")
  PAULLO$report <- (REPORT)

#POLLUTANTS PARAMETERS
LANDUSES <- read_excel("SECTIONS/LANDUSES.xlsx")
  PAULLO$landuses <- (LANDUSES)
POLLUTANTS <- read_excel("SECTIONS/POLLUTANTS.xlsx")
  PAULLO$pollutants <- (POLLUTANTS)
COVERAGES <- read_excel("SECTIONS/COVERAGES.xlsx")
  PAULLO$coverages <- (COVERAGES)
LOADINGS <- read_excel("SECTIONS/LOADINGS.xlsx")
  PAULLO$loadings <- (LOADINGS)
BUILDUP <- read_excel("SECTIONS/BUILDUP.xlsx")
  PAULLO$buildup <- (BUILDUP)
WASHOFF <- read_excel("SECTIONS/WASHOFF.xlsx")
  PAULLO$washoff <- (WASHOFF)
DWF <- read_excel("SECTIONS/DWF.xlsx")
  PAULLO$dwf <- unique(DWF)
PATTERNS <- read_excel("SECTIONS/PATTERNS.xlsx")
  PAULLO$patterns <- unique(PATTERNS)

#TIMESERIES FILE
PAULLO$timeseries <- tibble(
  Name = c("TS1"),
  Date = NA,
  Time = c("FILE"),
  Value = file.path(out_dir,"PIOGGE/TS0.dat")
)

summary(PAULLO)

write_inp(PAULLO, file.path(out_dir, "PAULLO.inp"))
```

**Comment by dickinsonre** [comment]
@dleutnant A past discussion on this problem can be seen here 

https://www.openswmm.org/Topic/26584/list-index-out-of-bound-0-error

**Comment by Enrilok** [comment]
@dickinsonre that post was in fact opened by me and I would have answered right now to write that I still have not been able to solve the problem, despite the fact that I have tried all your suggestions. In particular:

- I corrected the errors related to the polygons
- I corrected the problem of the coordinates that appear in the [JUNCTIONS] section
- I tried to rename the file as you suggested
- I got rid of the landuses I don't use

but unfortunately the moment I insert the [BUILDUP] and [WASHOFF] sections I keep getting the same error. Now, to be fair, I also report everything on OpenSWMM, but do you have any suggestions or other tests that I can do?
Thanks a lot to both of you for your help, I attach once again the correct .inp file which gives me the error.
[PAULLO_CORRECT.txt](https://github.com/dleutnant/swmmr/files/4644377/PAULLO_CORRECT.txt)

**Comment by dleutnant** [comment]
I fixed the issue with the geometry column. Also, I am able to run the model with the swmm5 engine (command line), BUT the GUI still gives the error message mentioned above.
@dickinsonre Maybe the GUI expects the sections to be ordered in a specific manner? If so, which is the correct order?

**Comment by dickinsonre** [comment]
the order of sections should not matter. though the options should be at top.  I can try randomizing a file to check for you though.
