### ISSUE TITLE
Issue with reading *.out file from 2D PCSWMM run

### ISSUE THREAD

**Issue by ashish-shrs** [dleutnant/swmmr#50]
I was using _read_out_ function to read time series of flooding, water depth from 1D and 2D model *.out file. Previously I was able to read *.out files from 2D simulations too. Now, i can read *.out from 1D simulation correctly but reading *.out file from 2D simulations has following issues:

This is the water depth in one of the 2D nodes as plotted using PCSWMM:
![Fig__1](https://user-images.githubusercontent.com/43453669/92162202-a5508500-ede6-11ea-8fe6-209751d65a3a.png)

But when i plot the same node's water depth using read_out function in R, it is reading the data incorrectly:
![Fig__2](https://user-images.githubusercontent.com/43453669/92162282-c6b17100-ede6-11ea-9c48-9a73b69406a1.png)

The y-axis magnitude is different from the figure above. Only attributes with magnitude that are above 1000 are the elevation or perhaps the invert elevations (as seen in top figure), and not the water depth.
![Fig__3](https://user-images.githubusercontent.com/43453669/92162414-f95b6980-ede6-11ea-9ae9-513a8a94be16.png)

I tried running _swmmr_ in both Mac and windows and couldn't solve this issue. I would appreciate your any suggestions. 

Thanks and Regards.
Ashish

**Comment by dleutnant** [comment]
Which R version do you use? Any chance that you create a reproducible example out of your model and upload the file in this thread?

**Comment by ashish-shrs** [comment]
I cannot provide the model files. Although I understand that would be helpful. I will reproduce out file if it is an only option. 

I just tried again in R 4.0.3. in Windows machine for different model results. I noticed that when the size of the *.out file is less than ~1GB, read_out function works fine. But if the size is larger > 3GB, it doesn't even read the file. I get the following error:

"Warning message:
In read_out(filelocation) : error reading out file"

Is there any size limitation on accessing binary *.out file by read_out? However, I am able to access report file using read_rpt for any model results.

**Comment by dleutnant** [comment]
#52

**Comment by ashish-shrs** [comment]
Thank you @dleutnant . I tried solution by @hsonne and now it works perfectly for large *.out file.

**Comment by dleutnant** [comment]
Great.
