### ISSUE TITLE
Error opening large .out file

### ISSUE THREAD

**Issue by jjsoper** [dleutnant/swmmr#52]
Hello, I am receiving the following error when trying to open a very large (10GB) out file. 

```
> read_out(file = model. .... [TRUNCATED]
$error
[1] 3
```
I have traced this to the OpenSwmmOutFile function:

```
> swmmr:::OpenSwmmOutFile(outFile = model.file)
$error
[1] 3
```

Any ideas on what this error is referencing? I haven't had any issues so far when working with smaller sized files, so thinking that may be the issue. 

Thanks,
Josh

**Comment by dleutnant** [comment]
Indeed, .out files exceeding 2 GB are currently not supported (due to ftell https://stackoverflow.com/questions/16696297/ftell-at-a-position-past-2gb). @hsonne didn't you find a general solution to this?

**Comment by hsonne** [comment]
Hi @dleutnant, sorry for not responding, I was on vacation. Without any further check, it seems that I worked on the issue on the "mydev" branch of my fork of your repo: https://github.com/hsonne/swmmr/tree/mydev. You may try to install the package from there: 
```
install.packages("remotes")
remotes::install_github("hsonne/swmmr@mydev")
```

**Comment by dleutnant** [comment]
That's great! Are you interested in pulling you modifications to the official branch?

**Comment by jjsoper** [comment]
Can confirm that this works on my machine. Thanks!

**Comment by hsonne** [comment]
@jjsoper I am glad to hear that. 
@dleutnant Yes, I am interested. However, I cannot do it right now. I remember that I did many changes and I need some time to recap what I did. Unfortunately, I do not have the time right now.

**Comment by dleutnant** [comment]
No worries, take your time! :-)

**Comment by gaoxiangying** [comment]
@hsonne ,@dleutnant, remotes::install_github("hsonne/swmmr@mydev") and remotes::install_github("dleutnant/swmmr@dev"), I have tried both, and it shows that "Error: Failed to install 'swmmr' from GitHub:
  Timeout was reached: [api.github.com] Connection timed out after 10000 milliseconds"
any suggestion for it? Thanks!

**Comment by gaoxiangying** [comment]
Downloading GitHub repo dleutnant/swmmr@dev
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/dleutnant/swmmr/tarball/dev'
another error

**Comment by dleutnant** [comment]
@gaoxiangying This is rather a network (behind a proxy?) or access issue and most probably not related to {swmmr}. Please check if you can generally install a package from github.

**Comment by gaoxiangying** [comment]
@dleutnant  Thanks!

**Comment by hsonne** [comment]
Hi @dleutnant! Long time no see! I have a question: Where is your `dev` branch? You already pulled some of my changes (#22, #23, #27, #28). I wanted to continue based on that branch.

**Comment by dleutnant** [comment]
Hi @hsonne! That's cool, looking forward to your contributions! 
Well, there isn't an official dev branch anymore. I use the main branch as the one with the latest developments, which eventually incorporates developments from other branches. (btw: I'm currently on paternity leave and very slow with responds ;) )

**Comment by hsonne** [comment]
The corresponding changes are now available on the `dev` branch of this repository. 
You can install the package from there with `remotes::install_github("dleutnant/swmmr@dev")`.
