### ISSUE TITLE
Multiparameter autocalibration using SWMMR

### ISSUE THREAD

**Issue by mrament** [dleutnant/swmmr#55]
Hello, 
I've been using the example autocalibration code to calibrate 1 parameter at a time and it works great. However, I recently tried modifying the code to calibrate three parameters at once. To do this, I added the following code chunks to obj_fun() : 
inp$subcatchment<- transform(inp$subcatchment, Perc_Imperv=ifelse(Area>.01, x, Perc_Imperv) 
inp$subcatchment<- transform(inp$subcatchment, Width=ifelse(Area>.01, x, Width) 
inp$subcatchment<- transform(inp$infiltration, Ksat=ifelse(Suction>.01, x, Ksat)

This would allow the program to simultaneously modify the values of Perc_Imperv, Width, and Ksat. I also supplied 2 additional vectors to the "upper" and "lower" prompts in the optimization code to provide parameter bounds for Width and Ksat. This approach worked in the sense that it generated a list of optimal parameter values that minimized the -NSE value. But, when I then plugged those values into SWMM, my output was pretty bad and the NSE of my new model didn't come close to matching the supposed NSE of the optimized model output. I was therefore wondering if anyone sees any flaws in this approach, or if anyone has developed a multiparameter autocalibration function that works. Thanks!

**Comment by dickinsonre** [comment]
The width determines the peak flow, percent impervious determines the impervious flow volume, and the amount of rainfall on pervious surfaces.  Ksat determines the infiltration loss which affects the pervious area runoff.  The same width is applied to both impervious and pervious runoff surfaces,  I would add roughness as well as Width/roughness is different for pervious and impervious surfaces.

**Comment by dleutnant** [comment]
I'm not quite sure if your code is correct.
Please be aware, that `x` is a vector and thus you should probably access its elements via `x[1]`, `x[2]`, etc. in case you would like to estimate multiple parameters. I recommend to play a bit with the DEoptim package to check the correct setup for multiple parameters.

Additionally,  `inp$subcatchment<- transform(inp$infiltration, Ksat=ifelse(Suction>.01, x, Ksat)` should probably changed to `inp$infiltration<- ...  `

**Comment by dleutnant** [comment]
@mrament Is your issue solved?

**Comment by mrament** [comment]
Hi Dominik,

Thanks for following up on this, I appreciate it. No, I was not able to figure out how to get the program to successfully run for more than 1 parameter. It will run, but the NSE values it derives are not accurate. Have you developed any example code for multiparameter autocalibration? If so, that'd be very helpful. Thanks!

Mike

________________________________

**Comment by joelnc** [comment]
Hi @mrament.  Check out closed issue 61.  Does that help out?

https://github.com/dleutnant/swmmr/issues/61#issuecomment-764827135
