### ISSUE TITLE
Running *.inp file after I edit it in R

### ISSUE THREAD

**Issue by ashish-shrs** [dleutnant/swmmr#57]
I am trying to change the rainfall and parameter value of the input file and trying to re-run it in R without having to save the *.inp file with new edit and read it again and run. My question is can I do that? And my issue is as below:

_inp = read_inp("D:/Model_Issues/Model_1.inp")_ # Here, I read the inp file

_for (j in 1:length(inp$subcatchments$Name)){_ # Here, I changed old rain gauge to new one 
  _inp$subcatchments$`Rain Gage`[j] = "NEW_Raindata"_
_}_

_run_swmm(inp)_ # So, I am trying to run that edited inp file. This command doesn't work. The issue is how do I make this input file run, since I changed something in *.inp file

_run_swmm("Model_1.inp")_ # Only way I could run it is from this command which means it is reading from the directory. So I have to save the above edits in *.inp using _write_inp_ and read it again before I could run it. And doing this gave me issue #56 

Looking forward to your tips/suggestions. Thanking you and regards.

**Comment by dleutnant** [comment]
`run_swmm()` calls the SWMM5 engine which is in fact the SWMM5.exe. This implies that a model input file (.inp) needs to be physically on disk. The system call for MS Windows basically is "c:/Program Files (x86)//EPA SWMM 5.1.015/swmm5.exe path_to_input.inp path_to_report.rpt path_to_binary_out.out". 

The alternative would be to integrate the full SWMM5 code into R which would be doable but requires substantial efforts. 
One would then have the full simulation within the R environment which means one could store all simulation results in RAM with all its pros and cons.
