### ISSUE TITLE
SWMM executable not found..

### ISSUE THREAD

**Issue by Sureshhett** [dleutnant/swmmr#65]
I get this warning when I run the swmmr library and run_swmm gives Error in file.exists(exec) : invalid 'file' argument.
all he commands were working fine and this started up with no change to any code in my script

much thanks for any help

**Comment by dleutnant** [comment]
Where lives your SWMM executable file? 
What does `getOption("swmmr.exec")` print?

When the swmmr package is installed, it tries to find the executable in common directories and saves the file path in the R option "swmmr.exec". If you did install swmmr first, without a SWMM Version being installed, swmmr cannot find the executable and the option gets `NULL`. 
If swmmr cannot find the executable, you still can set the `exec` parameter of `swmmr::run_swmm`.

Please check also the help file of `run_swmm`, i.e. `?swmmr::run_swmm`.

**Comment by Sureshhett** [comment]
Thanks for the response

Ur thoughts were right on
After swmm was ‘corrupted ’ because of that power outage, reinstalling it in the colorectal location was the issue

I managed to get things resolved, using these suggestions among others

Much thanks again

Suresh

On 13 Jul 2021, at 20:56, Dominik Leutnant ***@***.***> wrote:

﻿

Where lives your SWMM executable file?
What does getOption("swmmr.exec") print?

When the swmmr package is installed, it tries to find the executable in common directories and saves the file path in the R option "swmmr.exec". If you did install swmmr first, without a SWMM Version being installed, swmmr cannot find the executable and the option gets NULL.
If swmmr cannot find the executable, you still can set the exec parameter of swmmr::run_swmm.

Please check also the help file of run_swmm, i.e. ?swmmr::run_swmm.
