### ISSUE TITLE
Cannot open input file XXX ... EPA-SWMM 5.1 (Build 5.1.15)

### ISSUE THREAD

**Issue by chun215** [dleutnant/swmmr#68]
Dear author of the code,

Thanks for this valuable tool for the SWMM model auto-calibration. Currently I am facing a issue to use executable engine of SWMM 5.1.015 to run model built in PCSWMM (version 7.4).
The error message received was 'Cannot open input file XXX ... EPA-SWMM 5.1 (Build 5.1.15)'.
Is there any way to troubleshoot such issue?
I have tried to open and run this inp file built under PCSWMM in EPA SWMM, it can run; besides, i also tried to open and save this file again in EPA SWMM, the use R code to run it, but still not working.

Looking forward your reply on this issue.

**Comment by dleutnant** [comment]
From [here](https://swmm5.org/2016/09/05/swmm-5-1-and-infoswmm-error-and-warning-messages/):

<html>
<body>


ERROR 303: | cannot open input file.The input file either does not exist or cannot be opened (e.g., it might be in use by another program).
-- | --



</body>
</html>

Does this help?

**Comment by chun215** [comment]
> From [here](https://swmm5.org/2016/09/05/swmm-5-1-and-infoswmm-error-and-warning-messages/):
> 
> ERROR 303:	cannot open input file.The input file either does not exist or cannot be opened (e.g., it might be in use by another program).
> Does this help?

Hi Dleutnant:

Thanks for your prompt reply. I think I solve this issue. same as another user's solution is to change the work directory to the inp file location.

But i am facing another issue now. i will try to figure it out whether due to my code rather than the swmmr function package.
