### ISSUE TITLE
Trying to use autocalibrate vignrette, getting Error: can not allocate vector of size

### ISSUE THREAD

**Issue by aroseboro** [dleutnant/swmmr#69]
Hi Dominik,

I am still very much a beginner when it comes to R. I am trying to run your autocalibrate vignette, but I swapped in a new .inp file I got from a practice model on PCSWMM and a new observed data file.

`library(DEoptim); library(purrr); library(swmmr)`
```
# inp_path <- Path through my C drive ending the .inp file

file_swmm_ran = run_swmm(
  inp = inp_path
)
```

```
read_rpt(file_swmm_ran$rpt) # this line isn't important for this issue
observed_csv= read.csv("PCSWMM_outfall_obs_csvform.csv")
```

inp <- read_inp(file_swmm_ran$inp)

nse <- function(x) {
  1 - sum((x[, 1] - x[, 2]) ^ 2) / sum((x[, 1] - mean(x[, 1])) ^ 2)
}

```

obj_fun <- function(x, inp, observed_csv) {
  
  # set new parameters and update inp object
  inp$subcatchments <- transform(
    inp$subcatchments,
    Perc_Imperv = ifelse(Area > 2, x, Perc_Imperv)
  )

  
  # write new inp file to disk
  tmp_inp <- tempfile()
  write_inp(inp, tmp_inp)
  
  # run swmm with new parameter set
  file_swmm_ran <- suppressMessages(run_swmm(tmp_inp, stdout = NULL))
  
  # remove files when function exits to avoid heavy disk usage
  on.exit(file.remove(unlist(file_swmm_ran)))
  
  # read sim result
  sim <- read_out(
    file = file_swmm_ran$out, # path to out file
    iType = 1, # type: node
    object_name = "Outfall", # name of node
    vIndex = 4 # parameter at node: total inflow
  )[["Outfall"]]$total_inflow # directly access to xts object

```  
```
  # calculate goodness-of-fit
  # note: multiply by minus one to have a real min problem (nse: +1 to -Inf)
  nse(merge(observed_csv, sim)) * -1
}
```

```
set.seed(84) # to get reproducible results

calibration_res <- DEoptim(
  fn = obj_fun, 
  lower = c(0, 0), 
  upper = c(100, 100),
  control = list(
    itermax = 10, # maximum iterations
    trace = 1, # print progress every 10th iteration
    packages = c("swmmr"), # export packages to optimization environment
    parVar = c("nse"), # export function to optimization environment
    parallelType = 0 # set to 1 to use all available cores
  ),
  inp = inp, # 'inp' object
  observed_csv = observed_csv # xts object containing observation data
)

summary(calibration_res)'

```
In the end, this returns an error that says Error: cannot allocate vector of size 17.1 gb

A couple notes:

The csv file I am using is over 65000 rows long, compared to the approximately 20 rows in the example you used. 
I also tried to messing around with the number of interations and that didn't either.
The observed data from PCSWMM came as a .TSB file, which I could not open in R so I had to covert it into a .csv

Thank you in advance!

**Comment by dleutnant** [comment]
What is the size of the .out file?

**Comment by aroseboro** [comment]
The .out file in my test is 53109 KB, compared to 44 KB for the Example1 .out

**Comment by dleutnant** [comment]
What happens if you convert your obs data as {xts} object beforehand?

**Comment by dleutnant** [comment]
Any updates?

**Comment by aroseboro** [comment]
Hi,
Sorry for the late response. I am having difficulty converting it into a xts. I will close the issue and open a new one if I can get it figured out.
