### ISSUE TITLE
Asking for Sample.out file to run the model

### ISSUE THREAD

**Issue by DINBOR** [dleutnant/swmmr#74]
I wrote the file to .inp and named it "Sample.inp". 

However, while executing " run_swmm()", got the following error.
--------------------------------------------------
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="Model/Sample1.out": The system cannot find the file specified
----------------------------------------------------------
Can anyone please help me understand the error.
Thanks

**Comment by dleutnant** [comment]
Please check the .rpt file. There is probably something wrong and your model run didn't succeed (This means, there is no .out file and the system cannot finf the file specified).
