### ISSUE TITLE
The deprecated function was probably used in the swmmr package.

### ISSUE THREAD

**Issue by RonaldoAG** [dleutnant/swmmr#84]
Warning messages:
1: `as.tibble()` was deprecated in tibble 2.0.0.
i Please use `as_tibble()` instead.
i The signature and semantics have changed, see `?as_tibble`.
i The deprecated feature was likely used in the swmmr package.
  Please report the issue at <https://github.com/dleutnant/swmmr/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
2: `spread_()` was deprecated in tidyr 1.2.0.
i Please use `spread()` instead.
i The deprecated feature was likely used in the swmmr package.
  Please report the issue at <https://github.com/dleutnant/swmmr/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by hsonne** [comment]
Hello @RonaldoAG, thanks for your report. I was asked by @dleutnant to help him maintain this package. I replaced the function calls that caused the warnings with the recommended counterparts. The changes are available on the `dev` branch of this repository. You can install the package from there with `remotes::install_github("dleutnant/swmmr@dev")`.
